Add check target to makefile and use docker to build wasm

diff --git a/fetch_and_process_api_call/Makefile b/fetch_and_process_api_call/Makefile
--- a/fetch_and_process_api_call/Makefile
+++ b/fetch_and_process_api_call/Makefile
@@ -2,20 +2,29 @@ default: run
 
 tmp:
 	@mkdir -p tmp
+
+check:
+	@command -v docker >/dev/null 2>&1 || { echo >&2 "docker not found in PATH. Aborting."; exit 1; }
+	@command -v bky-as >/dev/null 2>&1 || { echo >&2 "bky-as not found in PATH. Aborting."; exit 1; }
+	@command -v jq >/dev/null 2>&1 || { echo >&2 "jq not found in PATH. Aborting."; exit 1; }
 	
-tmp/x.wasm: main.go $(wildcard as/*.go) | tmp
+tmp/x.wasm: main.go $(wildcard as/*.go) | tmp check
 	@echo "Building WASM module..."
-	@tinygo build -o tmp/x.wasm -target=wasi main.go
+	@docker run --rm \
+        -v .:/src \
+        -w /src \
+        --platform linux/amd64 \
+        tinygo/tinygo:0.31.2 \
+        tinygo build -o tmp/x.wasm -target=wasi main.go
 
 build: tmp/x.wasm
 
-run: build
+run: build | check
 	@echo "Running WASM module..."
-	@export PATH=$$PATH:$(pwd) && \
-	cat fn-call.json \
+	@cat fn-call.json \
 	| bky-as attest-fn-call \
 	| jq -r '.function_calls[0].claims.output | @base64d | fromjson'
 
 clean:
-	rm -rf tmp
+	@rm -rf tmp
 
