[BKY-6950] Rimble fetch match id bky 6950 (#66)
* Add step for fetching a recent rimble match id and date. Pass these when running examples test

* Update targets to template match id and date. Add helper target for fetching a recent match id. Fix default target

* Update TeamKillDiff to use all games in match not just games for a particular map. Fix typo in error message

* Add Date field as that is also returned in match response

* Update rimble test now that match id and date are passed in as env vars

diff --git a/.github/workflows/on-prs.yml b/.github/workflows/on-prs.yml
--- a/.github/workflows/on-prs.yml
+++ b/.github/workflows/on-prs.yml
@@ -47,12 +47,32 @@ jobs:
         with:
           nix_path: nixpkgs=channel:nixos-24.11
 
+      - name: Fetch Recent Match ID
+        run: |
+          response=$(curl --fail --location \
+              -H 'x-api-key: ${{ secrets.RIMBLE_API_KEY }}' \
+              'https://rimbleanalytics.com/raw/csgo/completed-matches/')
+          
+          match_date=$(echo "$response" | jq -r '.[0].date')
+          match_id=$(echo "$response" | jq -r '.[0].matchid')
+          
+          if [ -z "match_date" ] || [ -z "match_id" ]; then
+            echo "Error: One or more response values are empty."
+            echo "Response: $response"
+            exit 1
+          fi
+
+          echo "RIMBLE_MATCH_DATE=${match_date}" >> "$GITHUB_ENV"
+          echo "RIMBLE_MATCH_ID=${match_id}" >> "$GITHUB_ENV"
+
       - name: Run Tests
         env:
           GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
           YOUR_COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
           YOUR_DHL_API_KEY: ${{ secrets.DHL_API_KEY }}
           YOUR_RIMBLE_API_KEY: ${{ secrets.RIMBLE_API_KEY }}
+          YOUR_RIMBLE_MATCH_DATE: ${{ env.RIMBLE_MATCH_DATE }}
+          YOUR_RIMBLE_MATCH_ID: ${{ env.RIMBLE_MATCH_ID }}
         run: |
           nix-shell \
             --pure \
@@ -65,6 +85,8 @@ jobs:
             --keep YOUR_COINGECKO_API_KEY \
             --keep YOUR_DHL_API_KEY \
             --keep YOUR_RIMBLE_API_KEY \
+            --keep YOUR_RIMBLE_MATCH_DATE \
+            --keep YOUR_RIMBLE_MATCH_ID \
             --run "\
             go test -C test . -count=1 -v -run=TestCoinPricesFromCoingecko && \
             go test -C test . -count=1 -v -run=TestErrorHandlingAttestFnCall && \
